import { chmodSync, mkdirSync, readFileSync, readdirSync, renameSync, rmSync, writeFileSync } from "node:fs"; import { join } from "node:path"; import { AGENT_READABLE_SKILL_DIR_MODE, AGENT_READABLE_SKILL_FILE_MODE, serializeWorkflowFile } from "../../../shared/workflow-model.js"; import { isSafeFolderId } from "../../storage/folder-id.js";
export const MANAGED_SKILLS_DIRNAME = "managed-skills"; export const MANAGED_SKILLS_CACHE_FILENAME = "cache.json"; export const MANAGED_SKILL_FILES_DIRNAME = "skills"; export interface ManagedSkill { id: string; name: string; description: string; body: string } export interface ManagedSkillsCache { fetchedAt: number; skills: ManagedSkill[] }
export function getManagedSkillsDir(sandRoot: string): string { return join(sandRoot, MANAGED_SKILLS_DIRNAME); } export function getManagedSkillsCachePath(cacheDir: string): string { return join(cacheDir, MANAGED_SKILLS_CACHE_FILENAME); } export function getManagedSkillFilePath(cacheDir: string, id: string): string { return join(cacheDir, MANAGED_SKILL_FILES_DIRNAME, id, "SKILL.md"); }
/**
 * The id becomes a directory name under skills/, so a row that would escape that directory is not
 * a skill. `writeManagedSkillsCache` used to be reachable only from a fetch, whose rows are
 * normalized by `fetchedManagedSkillToSandSkill` and already checked; `ensureSeeds` writes the
 * cache back from cache.json's own content, so the read side is now the only place that check can
 * happen and a mangled row has to be dropped here rather than materialized at whatever path it
 * names.
 */
export function isManagedSkill(value: unknown): value is ManagedSkill { if (typeof value !== "object" || value == null) return false; const skill = value as Record<string, unknown>; return isSafeFolderId(skill.id) && typeof skill.name === "string" && typeof skill.description === "string" && typeof skill.body === "string" && skill.body.length > 0; }
export function readManagedSkillsCache(cacheDir: string): ManagedSkillsCache | null { try { const parsed = JSON.parse(readFileSync(getManagedSkillsCachePath(cacheDir), "utf8")) as Record<string, unknown>; return typeof parsed.fetchedAt === "number" && Number.isFinite(parsed.fetchedAt) && Array.isArray(parsed.skills) && parsed.skills.every(isManagedSkill) ? { fetchedAt: parsed.fetchedAt, skills: parsed.skills } : null; } catch { return null; } }
export function writeManagedSkillsCache(cacheDir: string, skills: readonly ManagedSkill[], now: () => number = Date.now): void { const body = `${JSON.stringify({ fetchedAt: now(), skills }, null, 2)}\n`; mkdirSync(cacheDir, { recursive: true, mode: AGENT_READABLE_SKILL_DIR_MODE }); chmodSync(cacheDir, AGENT_READABLE_SKILL_DIR_MODE); const path = getManagedSkillsCachePath(cacheDir), temp = `${path}.tmp`; writeFileSync(temp, body, { encoding: "utf8", mode: AGENT_READABLE_SKILL_FILE_MODE }); chmodSync(temp, AGENT_READABLE_SKILL_FILE_MODE); renameSync(temp, path); materializeManagedSkillFiles(cacheDir, skills); }
/** The bytes the agent reads for a cache row, so a check can compare the two rather than just look for a file. */
export function managedSkillFileContent(skill: ManagedSkill): string { return serializeWorkflowFile({ name: skill.name, description: skill.description, body: skill.body, trigger: null }); }
/**
 * A managed skill is two files and both have to say the same thing: cache.json is what an
 * invocation inlines into the prompt, skills/<id>/SKILL.md is the path the agent is handed and the
 * only copy it can read for itself. Checking that the file merely exists let the two drift apart
 * and stay apart, so this compares the file to what the row would write.
 */
export function managedSkillFilesMatch(cacheDir: string, skills: readonly ManagedSkill[]): boolean { return skills.every((skill) => { try { return readFileSync(getManagedSkillFilePath(cacheDir, skill.id), "utf8") === managedSkillFileContent(skill); } catch { return false; } }); }
export function materializeManagedSkillFiles(cacheDir: string, skills: readonly ManagedSkill[]): void { const filesDir = join(cacheDir, MANAGED_SKILL_FILES_DIRNAME); mkdirSync(filesDir, { recursive: true, mode: AGENT_READABLE_SKILL_DIR_MODE }); chmodSync(filesDir, AGENT_READABLE_SKILL_DIR_MODE); const keep = new Set(skills.map((skill) => skill.id)); for (const entry of readdirSync(filesDir, { withFileTypes: true })) if (!keep.has(entry.name)) rmSync(join(filesDir, entry.name), { recursive: true, force: true }); for (const skill of skills) { const skillDir = join(filesDir, skill.id); mkdirSync(skillDir, { recursive: true, mode: AGENT_READABLE_SKILL_DIR_MODE }); chmodSync(skillDir, AGENT_READABLE_SKILL_DIR_MODE); const path = getManagedSkillFilePath(cacheDir, skill.id), temp = `${path}.tmp`; const content = managedSkillFileContent(skill); writeFileSync(temp, content, { encoding: "utf8", mode: AGENT_READABLE_SKILL_FILE_MODE }); chmodSync(temp, AGENT_READABLE_SKILL_FILE_MODE); renameSync(temp, path); } }
