// CLOUD-BROWSER-1. The driver's cloud leg: the socket, the address guard, the no-content verdict.
//
// These three are the things that would be silently wrong if the cloud browser had been built as a
// second implementation on the host side instead of as a second leg of the same driver:
//
//   - a wss:// endpoint has to speak the same WebSocket the box's ws:// one does, and anything that
//     is neither has to be refused rather than turned into some other kind of request;
//   - checkPublicWebUrl -- the guard that RESOLVES a name and refuses a public host landing on a
//     private address -- has to run on the cloud path too. It is the second of the two address
//     guards and the only one that catches localtest.me;
//   - the emptyShell verdict has to fire on the page it was written for and stay quiet on a page
//     that is simply small.
//
// No box, no network, no key. Seconds.

import test from "node:test";
import assert from "node:assert/strict";
import net from "node:net";
import tls from "node:tls";
import crypto from "node:crypto";

import { connectWebSocket, acceptKey, encodeFrame, OPCODE } from "../runtime/browser-driver/ws.mjs";
import { checkPublicWebUrl, NOT_PUBLIC_WEB } from "../runtime/browser-driver/driver.mjs";
import { analyzePage, detectEmptyShell, EMPTY_SHELL_MIN_HTML_BYTES } from "../runtime/browser-driver/page-text.mjs";

/* ------------------------------------------------------------------ a TLS websocket server */

// A self-signed pair, made here so the test carries no key file. `rejectUnauthorized: false` is
// passed by the TEST only -- production leaves the flag at true, and ws.mjs names it on the line
// rather than defaulting it so that turning it off anywhere else is a visible edit.
function selfSigned() {
  const { privateKey, publicKey } = crypto.generateKeyPairSync("rsa", { modulusLength: 2048 });
  return { privateKey, publicKey };
}

/** Answers one WebSocket handshake and echoes one text frame back. */
function startEchoServer({ secure }) {
  const onConnection = (socket) => {
    let head = Buffer.alloc(0);
    const onData = (chunk) => {
      head = Buffer.concat([head, chunk]);
      const end = head.indexOf("\r\n\r\n");
      if (end === -1) return;
      socket.removeListener("data", onData);
      const headerText = head.subarray(0, end).toString("latin1");
      const key = /sec-websocket-key:\s*(\S+)/i.exec(headerText)?.[1] ?? "";
      socket.write(
        "HTTP/1.1 101 Switching Protocols\r\n"
        + "Upgrade: websocket\r\nConnection: Upgrade\r\n"
        + `Sec-WebSocket-Accept: ${acceptKey(key)}\r\n\r\n`,
      );
      // One unmasked text frame, which is what a server sends.
      socket.write(encodeFrame(OPCODE.text, JSON.stringify({ hello: "browser" }), { mask: false }));
    };
    socket.on("data", onData);
    socket.on("error", () => undefined);
  };

  if (!secure) {
    const server = net.createServer(onConnection);
    return new Promise((resolve) => server.listen(0, "127.0.0.1", () => resolve({ server, port: server.address().port })));
  }
  const { privateKey } = selfSigned();
  // node:crypto cannot mint an X.509 certificate, so the TLS leg is proved against a certificate
  // node ships for exactly this: a throwaway pair generated by tls.createSecureContext is not
  // available either, so the secure leg is asserted through its refusal path instead (below) and
  // its socket wiring is exercised by the plain leg, which shares every line but the connect call.
  void privateKey;
  return Promise.resolve(null);
}

test("ws.mjs speaks the same WebSocket, and does not drop a frame that rides with the handshake", async () => {
  // The server writes its frame in the same breath as the 101, which is what a vendor endpoint that
  // greets its client does and what the box's Chrome never does. Before this wave that frame was
  // parsed and thrown away, because the constructor drains `leftover` before connectWebSocket has
  // resolved and therefore before any caller can register a handler -- a hang with nothing to read.
  const { server, port } = await startEchoServer({ secure: false });
  try {
    const socket = await connectWebSocket(`ws://127.0.0.1:${port}/devtools/browser/abc`, { timeoutMs: 5000 });
    const message = await new Promise((resolve, reject) => {
      const timer = setTimeout(() => reject(new Error("the first frame was dropped")), 4000);
      socket.onMessage((text) => { clearTimeout(timer); resolve(text); });
    });
    assert.equal(JSON.parse(message).hello, "browser");
    socket.close();
  } finally {
    server.close();
  }
});

test("ws.mjs refuses any scheme that is not ws or wss", async () => {
  for (const url of ["http://127.0.0.1:1/x", "https://example.com/x", "file:///etc/passwd", "javascript:1"]) {
    await assert.rejects(
      async () => await connectWebSocket(url, { timeoutMs: 200 }),
      (error) => /only speaks ws:\/\/ and wss:\/\//.test(error.message),
      `expected ${url} to be refused`,
    );
  }
});

test("ws.mjs takes the wss leg and reaches for TLS rather than a plain socket", async () => {
  // Nothing is listening, so the connect fails -- the point is WHICH way it failed. A wss URL that
  // fell through to net.connect would fail with a bare connection error; taking the TLS leg is what
  // the module's own error text and the port default prove. Port 443 by default is the tell: a
  // wss:// URL with no port must not be dialled on 80.
  const started = [];
  const originalConnect = tls.connect;
  tls.connect = (options, ...rest) => {
    started.push(options);
    return originalConnect.call(tls, { ...options, port: 1 }, ...rest);
  };
  try {
    await assert.rejects(async () => await connectWebSocket("wss://127.0.0.1/devtools/browser/abc", { timeoutMs: 400 }));
    assert.equal(started.length, 1, "the wss leg must go through node:tls");
    assert.equal(started[0].port, 443, "a wss URL with no port is 443, never 80");
    assert.equal(started[0].servername, "127.0.0.1");
    assert.equal(started[0].rejectUnauthorized, true, "certificate checking stays on: the endpoint IS the credential");
  } finally {
    tls.connect = originalConnect;
  }
});

/* ------------------------------------------------------------------ the second address guard */

test("checkPublicWebUrl still refuses a public name that resolves to a private address", async () => {
  // This is the guard a host-side re-implementation of the cloud browser would have dropped, and it
  // is the only one of the two that catches this case: the name is public, so the literal-address
  // check in the host passes it, and only a real lookup finds where it lands.
  const resolve = async (host) => {
    assert.equal(host, "localtest.me");
    return [{ address: "127.0.0.1", family: 4 }];
  };
  await assert.rejects(
    async () => await checkPublicWebUrl("https://localtest.me/internal", { resolve }),
    (error) => error.message === NOT_PUBLIC_WEB,
  );
});

test("checkPublicWebUrl passes an ordinary public address, on the cloud path as on the box path", async () => {
  const resolve = async () => [{ address: "93.184.216.34", family: 4 }];
  assert.equal(await checkPublicWebUrl("example.com", { resolve }), "https://example.com");
});

test("checkPublicWebUrl still refuses a scheme that is not the web", async () => {
  for (const url of ["file:///etc/passwd", "chrome://settings", "ftp://example.com"]) {
    await assert.rejects(async () => await checkPublicWebUrl(url, {}), (error) => error.message.startsWith(NOT_PUBLIC_WEB));
  }
});

/* ------------------------------------------------------------------ the no-content verdict */

// The measured page, rebuilt from what grok-bot-local-vm read on 2026-09-09: a 620 kB document that
// answered 200 with needsLogin false, blocked false, and Meta's footer chrome as its entire text.
// The markup is padding because the markup is not what the verdict reads -- the extracted text is,
// and this reproduces the extracted text exactly: short link-shaped lines and nothing else.
const INSTAGRAM_FOOTER_WORDS = [
  "Meta", "About", "Blog", "Jobs", "Help", "API", "Privacy", "Terms", "Locations",
  "Instagram Lite", "Threads", "Contact Uploading & Non-Users", "Meta Verified",
  "English", "Afrikaans", "Deutsch", "Espanol", "Francais",
];
const INSTAGRAM_SHELL_HTML = `<html><head><title>Titanium Computing (@titaniumcomputing) &#8226; Instagram photos and videos</title></head>`
  + `<body><div id="mount_0_0_aB">${"<div class=\"x1n2onr6\"><span></span></div>".repeat(9000)}</div>`
  + `<footer><ul>${INSTAGRAM_FOOTER_WORDS.map((word) => `<li><a href="#">${word}</a></li>`).join("")}</ul>`
  + `<span>&#169; 2026 Instagram from Meta</span></footer></body></html>`;

// example.com as it really is: 559 bytes, 131 characters of readable text, and a whole page.
const EXAMPLE_HTML = `<!doctype html><html><head><title>Example Domain</title></head><body><div>`
  + `<h1>Example Domain</h1><p>This domain is for use in illustrative examples in documents. You may use this domain `
  + `in literature without prior coordination or asking for permission.</p><p><a href="https://www.iana.org/domains/example">More information...</a></p>`
  + `</div></body></html>`;

test("the captured Instagram body is big enough for the rule to even apply", () => {
  assert.ok(
    INSTAGRAM_SHELL_HTML.length >= EMPTY_SHELL_MIN_HTML_BYTES,
    `the fixture must be a heavy document; it is ${INSTAGRAM_SHELL_HTML.length} bytes`,
  );
});

test("emptyShell fires on the captured Instagram body", () => {
  const analysis = analyzePage({ html: INSTAGRAM_SHELL_HTML, innerText: "", title: "Titanium Computing", url: "https://www.instagram.com/titaniumcomputing/", status: 200 });
  assert.equal(analysis.needsLogin, false, "the measured page did not ask for a sign-in, which is the whole problem");
  assert.equal(analysis.blocked, false, "and it was not blocked either");
  assert.equal(analysis.emptyShell, true, "so the third verdict is the only thing that can catch it");
  assert.ok(analysis.emptyShellReason.length > 0);
});

test("emptyShell does NOT fire on the captured example.com body", () => {
  const analysis = analyzePage({ html: EXAMPLE_HTML, innerText: "", title: "Example Domain", url: "https://example.com/", status: 200 });
  assert.equal(analysis.emptyShell, false, "a small page that said something is a page, not a shell");
  assert.ok(analysis.text.includes("illustrative examples"));
});

test("emptyShell does not steal a verdict from a sign-in wall or a challenge page", () => {
  const wall = `<html><head><title>Log in</title></head><body>${"<div></div>".repeat(9000)}`
    + `<form><input type="password" name="p" /><button>Log in</button></form></body></html>`;
  const walled = analyzePage({ html: wall, innerText: "", title: "Log in", url: "https://example.com/login", status: 200 });
  assert.equal(walled.needsLogin, true);
  assert.equal(walled.emptyShell, false, "a sign-in wall is described as a sign-in wall, not as an empty page");

  const challenge = analyzePage({ html: `<html><body><p>Verify you are human</p></body></html>`, innerText: "", title: "Just a moment", url: "https://example.com/", status: 200 });
  assert.equal(challenge.blocked, true);
  assert.equal(challenge.emptyShell, false);
});

test("a page whose whole text is its own title is an empty shell whatever its size", () => {
  // TOOLS-FETCH-3's case, which is why the title clause does not carry the big-body requirement.
  assert.equal(detectEmptyShell({ text: "Reddit", title: "Reddit", html: "<html></html>" }).emptyShell, true);
  assert.equal(detectEmptyShell({ text: "Reddit\n\nA long article follows here with real sentences in it.", title: "Reddit", html: "<html></html>" }).emptyShell, false);
});

test("a heavy page carrying real prose is not a shell", () => {
  const article = `<html><head><title>A real article</title></head><body><article>`
    + `<p>${"The measured latency on this box was three seconds and change, which is slower than the same page read from the Mac. ".repeat(20)}</p>`
    + `</article>${"<div class=\"pad\"></div>".repeat(4000)}</body></html>`;
  const analysis = analyzePage({ html: article, innerText: "", title: "A real article", url: "https://example.com/a", status: 200 });
  assert.ok(article.length >= EMPTY_SHELL_MIN_HTML_BYTES);
  assert.equal(analysis.emptyShell, false);
});
