import { randomUUID } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { SAND_DISK_PRESSURE_REMINDERS_FILE_NAME } from "../../durable-file-policy.js";
import { getSandRootDir } from "../../host-paths.js";
import { createDiskPressureGuard, readDiskVolumeSnapshots, type DiskPressureLevel, type DiskPressureReport } from "./disk-pressure-guard.js";

export class SandDiskPressureLedgerError extends Error {}
export interface DiskPressureReminderEpisodes { claim(value: { agentId: string; claimId: string }): string | null; release(value: { agentId: string; claimId: string }): void; enroll(agentIds: Iterable<string>): void; commit(value: { agentId: string; claimId: string }): boolean; forgetAgent(agentId: string): void; observePressure(level: DiskPressureLevel, complete?: boolean): void }
function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null; }
function hasErrorCode(error: unknown, code: string): boolean { return isRecord(error) && error.code === code; }
export function createDiskPressureReminderEpisodes(options?: { readonly rootDir?: string; readonly createEpisodeId?: () => string; readonly onLedgerError?: (error: unknown) => void }): DiskPressureReminderEpisodes {
  const filePath = options?.rootDir === undefined ? undefined : join(options.rootDir, SAND_DISK_PRESSURE_REMINDERS_FILE_NAME); let activeEpisodeId: string | null = null, restoredEpisodeAwaitingPressure = false, activeEpisodePersistencePending = false; const handledAgentIds = new Set<string>(), pendingEpisodeIds = new Map<string, string[]>(), claims = new Map<string, { claimId: string; episodeId: string }>();
  const enqueue = (agentId: string, episodeId: string): boolean => { const pending = pendingEpisodeIds.get(agentId) ?? []; if (pending.includes(episodeId)) return false; pendingEpisodeIds.set(agentId, [...pending, episodeId]); return true; };
  if (filePath !== undefined) try { const parsed: unknown = JSON.parse(readFileSync(filePath, "utf8")); if (!isRecord(parsed) || parsed.version !== 1) throw new SandDiskPressureLedgerError("invalid disk-pressure reminder ledger"); activeEpisodeId = typeof parsed.activeEpisodeId === "string" ? parsed.activeEpisodeId : null; restoredEpisodeAwaitingPressure = activeEpisodeId !== null; if (activeEpisodeId !== null && Array.isArray(parsed.handledAgentIds)) for (const id of parsed.handledAgentIds) if (typeof id === "string") handledAgentIds.add(id); if (Array.isArray(parsed.pending)) for (const item of parsed.pending) if (isRecord(item) && typeof item.agentId === "string" && typeof item.episodeId === "string") enqueue(item.agentId, item.episodeId); } catch (error) { if (!hasErrorCode(error, "ENOENT")) options?.onLedgerError?.(error); }
  const createEpisodeId = options?.createEpisodeId ?? randomUUID;
  const persist = (): boolean => { if (filePath === undefined) return true; try { if (activeEpisodeId === null && pendingEpisodeIds.size === 0) { rmSync(filePath, { force: true }); return true; } const ledger = { version: 1, activeEpisodeId, handledAgentIds: activeEpisodeId === null ? [] : [...handledAgentIds], pending: [...pendingEpisodeIds].flatMap(([agentId, ids]) => ids.map((episodeId) => ({ agentId, episodeId }))) }; mkdirSync(dirname(filePath), { recursive: true }); writeFileSync(`${filePath}.part`, JSON.stringify(ledger)); renameSync(`${filePath}.part`, filePath); return true; } catch (error) { options?.onLedgerError?.(error); return false; } };
  return {
    claim({ agentId, claimId }) { const existing = claims.get(agentId); if (existing != null) return existing.claimId === claimId ? existing.episodeId : null; if (activeEpisodeId !== null && !handledAgentIds.has(agentId) && enqueue(agentId, activeEpisodeId)) persist(); const episodeId = pendingEpisodeIds.get(agentId)?.[0]; if (episodeId === undefined) return null; claims.set(agentId, { claimId, episodeId }); return episodeId; },
    release({ agentId, claimId }) { if (claims.get(agentId)?.claimId === claimId) claims.delete(agentId); },
    enroll(agentIds) { if (activeEpisodeId === null) return; let changed = false; for (const id of agentIds) if (!handledAgentIds.has(id)) changed = enqueue(id, activeEpisodeId) || changed; if (changed) persist(); },
    commit({ agentId, claimId }) { const claim = claims.get(agentId), pending = pendingEpisodeIds.get(agentId); if (claim?.claimId !== claimId || pending?.[0] !== claim.episodeId) return false; const remaining = pending.slice(1); if (remaining.length === 0) pendingEpisodeIds.delete(agentId); else pendingEpisodeIds.set(agentId, remaining); const alreadyHandled = handledAgentIds.has(agentId); if (activeEpisodeId === claim.episodeId) handledAgentIds.add(agentId); if (!persist()) { pendingEpisodeIds.set(agentId, pending); if (!alreadyHandled) handledAgentIds.delete(agentId); return false; } claims.delete(agentId); return true; },
    forgetAgent(agentId) { claims.delete(agentId); const changed = pendingEpisodeIds.delete(agentId) || handledAgentIds.delete(agentId); if (changed) persist(); },
    observePressure(level, complete = true) { if (level === "healthy") { if (activeEpisodeId === null || (!complete && restoredEpisodeAwaitingPressure)) return; } else if (activeEpisodeId !== null) { restoredEpisodeAwaitingPressure = false; if (activeEpisodePersistencePending && persist()) activeEpisodePersistencePending = false; return; } const oldId = activeEpisodeId, oldRestored = restoredEpisodeAwaitingPressure, oldHandled = [...handledAgentIds]; activeEpisodeId = level === "healthy" ? null : createEpisodeId(); restoredEpisodeAwaitingPressure = false; handledAgentIds.clear(); if (persist()) { activeEpisodePersistencePending = false; return; } if (level !== "healthy") { activeEpisodePersistencePending = true; return; } activeEpisodeId = oldId; restoredEpisodeAwaitingPressure = oldRestored; for (const id of oldHandled) handledAgentIds.add(id); },
  };
}

export const SAND_DISK_PRESSURE_WATCH_ENV = "SAND_HOST_DISK_PRESSURE";
const BOX_WORKSPACE_DIR = "/workspace";
// deps.isInBox is fed from SAND_HOST_IN_BOX, which nothing we ship sets, so this watch never armed and
// /workspace filled with no warning. Setting that variable is not the fix: it also starts box-log-shipper
// (../telemetry/box-log-shipper.ts) and switches host-upgrade into in-box mode. So disk pressure carries
// its own signal — SAND_HOST_DISK_PRESSURE forces it either way, otherwise we probe for the box's own
// workspace mount, which only exists inside the box.
export function isDiskPressureWatchEnabled(options: { readonly isInBox?: boolean; readonly env?: Record<string, string | undefined>; readonly probe?: (path: string) => boolean } = {}): boolean { const raw = (options.env ?? process.env)[SAND_DISK_PRESSURE_WATCH_ENV]?.trim().toLowerCase(); if (raw != null && raw.length > 0) return raw === "1" || raw === "true" || raw === "yes" || raw === "on"; return options.isInBox === true || (options.probe ?? existsSync)(BOX_WORKSPACE_DIR); }
export interface DiskPressureWatch { readonly level: "soft" | "hard" | null; readonly reminderEpisodes: DiskPressureReminderEpisodes; subscribe(listener: (level: "soft" | "hard" | null) => void): () => void; dispose(): void }
export function startDiskPressureWatch(deps: { readonly isInBox: boolean; readonly polling: { start(callback: () => Promise<void>): { dispose(): void } }; readonly report: (report: DiskPressureReport) => void; readonly log: (message: string) => void }): DiskPressureWatch { const listeners = new Set<(level: "soft" | "hard" | null) => void>(), watching = isDiskPressureWatchEnabled({ isInBox: deps.isInBox }); let level: "soft" | "hard" | null = null, guard: ReturnType<typeof createDiskPressureGuard> | undefined, polling: { dispose(): void } | undefined; const reminderEpisodes = createDiskPressureReminderEpisodes({ ...(watching ? { rootDir: getSandRootDir() } : {}), onLedgerError: (error) => deps.log(`disk-pressure reminder ledger failed: ${String(error)}`) }); deps.log(watching ? "disk-pressure watch armed" : `disk-pressure watch idle (no ${BOX_WORKSPACE_DIR}; set ${SAND_DISK_PRESSURE_WATCH_ENV}=1 to force it on)`); if (watching) { guard = createDiskPressureGuard({ readVolumes: () => readDiskVolumeSnapshots([{ volume: "workspace", path: BOX_WORKSPACE_DIR }, { volume: "sand_data", path: getSandRootDir() }, { volume: "temp", path: "/tmp" }]), report: deps.report, onPressureChange: (next) => { level = next; for (const listener of [...listeners]) listener(next); }, onSuccessfulSample: (next, complete) => reminderEpisodes.observePressure(next, complete), log: deps.log }); polling = deps.polling.start(async () => { guard?.onTick(); }); } return { get level() { return level; }, reminderEpisodes, subscribe(listener) { listeners.add(listener); return () => listeners.delete(listener); }, dispose() { polling?.dispose(); polling = undefined; guard?.dispose(); guard = undefined; listeners.clear(); } }; }
